FROM node:22-bookworm-slim

WORKDIR /app

RUN apt-get update -y \
	&& apt-get install -y --no-install-recommends openssl \
	&& rm -rf /var/lib/apt/lists/*

COPY package*.json ./
COPY .env.docker ./

RUN npm install

COPY src ./src
COPY prisma ./prisma
COPY tsconfig.json tsconfig.build.json nest-cli.json ./

RUN npx prisma generate && npm run build

CMD ["npm", "run", "start:dev"]

EXPOSE 3000